name: royaltrader
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  pdf: ^3.11.3
  printing: ^5.14.2
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  skeletonizer: ^1.4.3
  cached_network_image: ^3.4.1
  http: ^1.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
